<?php
// Builds data/dictionary.php, the only data file the game reads, from:
//   data/words.txt                 the word list, most common first
//   data/blocklist.txt             words that can never be played
//   data/categories.json           meaning categories (built by scripts/build-categories.py)
//   data/category-overrides.txt    hand corrections to the categories
//
//   php scripts/build-dictionary.php          rebuild
//   php scripts/build-dictionary.php --fetch  also re-download data/words.txt first
//
// data/words.txt holds common English words, most frequent first. A word must be
// in ENABLE (public domain) and in the OpenSubtitles frequency list from
// hermitdave/FrequencyWords (CC BY-SA 4.0).

declare(strict_types=1);

require __DIR__ . '/../src/WordFamilies.php';

const ENABLE_URL = 'https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt';
const FREQ_URL = 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_50k.txt';
const MAX_WORDS = 40000;
const MIN_LENGTH = 3;

$dataDir = dirname(__DIR__) . '/data';

if (in_array('--fetch', $argv, true)) {
    $enable = array_flip(array_map('trim', explode("\n", fetch(ENABLE_URL))));
    $words = [];
    foreach (explode("\n", fetch(FREQ_URL)) as $line) {
        $word = strtolower(trim(explode(' ', $line)[0]));
        if (strlen($word) < MIN_LENGTH || !preg_match('/^[a-z]+$/', $word)) continue;
        if (!isset($enable[$word]) || isset($words[$word])) continue;
        $words[$word] = true;
        if (count($words) >= MAX_WORDS) break;
    }
    file_put_contents("$dataDir/words.txt", implode("\n", array_keys($words)) . "\n");
    echo 'Wrote ' . count($words) . " words to data/words.txt\n";
}

$words = array_values(array_filter(array_map('trim', file("$dataDir/words.txt"))));

// Remove blocked words, together with their families.
$blocked = [];
foreach (readList("$dataDir/blocklist.txt") as $word) $blocked[$word] = true;
foreach (WordFamilies::build($words) as $members) {
    if (array_intersect_key(array_flip($members), $blocked)) {
        foreach ($members as $member) $blocked[$member] = true;
    }
}
$words = array_values(array_filter($words, fn ($w) => !isset($blocked[$w])));
$families = WordFamilies::build($words);

// Meaning categories, with hand corrections applied.
$categories = [];
foreach (json_decode(file_get_contents("$dataDir/categories.json"), true) as $id => $category) {
    $categories[$id] = ['label' => $category['label'], 'words' => array_fill_keys($category['words'], true)];
}
foreach (readList("$dataDir/category-overrides.txt") as $line) {
    [$id, $changes] = array_map('trim', explode(':', $line, 2)) + [1 => ''];
    if (!isset($categories[$id])) {
        fwrite(STDERR, "category-overrides.txt: unknown category \"$id\"\n");
        exit(1);
    }
    foreach (preg_split('/\s+/', $changes, -1, PREG_SPLIT_NO_EMPTY) as $change) {
        $word = strtolower(substr($change, 1));
        if ($change[0] === '+') $categories[$id]['words'][$word] = true;
        elseif ($change[0] === '-') unset($categories[$id]['words'][$word]);
    }
}
foreach ($categories as $id => $category) {
    // Keep dictionary order (most common first), and only allowed words.
    $categories[$id]['words'] = array_values(array_filter($words, fn ($w) => isset($category['words'][$w])));
}

$export = "<?php\n// Generated by scripts/build-dictionary.php. Do not edit by hand.\nreturn "
    . var_export(['words' => $words, 'families' => $families, 'categories' => $categories, 'blocked' => array_keys($blocked)], true) . ";\n";
file_put_contents("$dataDir/dictionary.php", $export);
echo 'Wrote data/dictionary.php: ' . count($words) . ' words (' . count($blocked) . ' blocked), '
    . count($families) . ' families, ' . count($categories) . " categories\n";

/** Non-empty lines of a text file, without # comments. */
function readList(string $path): array
{
    $lines = array_map(fn ($l) => trim(preg_replace('/#.*/', '', $l)), file($path));
    return array_values(array_filter($lines, 'strlen'));
}

function fetch(string $url): string
{
    $text = file_get_contents($url);
    if ($text === false) {
        fwrite(STDERR, "Could not download $url\n");
        exit(1);
    }
    return $text;
}
